allprojects {
    buildscript {
        repositories {
            all { ArtifactRepository repo ->
                if (repo instanceof MavenArtifactRepository) {
                    repo.allowInsecureProtocol = false
                }
            }
        }
    }
    repositories {
        all { ArtifactRepository repo ->
            if (repo instanceof MavenArtifactRepository) {
                repo.allowInsecureProtocol = false
            }
        }
    }
}
